import { ICookCardProps } from '@/components/types/types';

export const cards: ICookCardProps[] = [
    {
        foodId: 1,
        cookBy: 'knife',
        nameFood: 'салат',
        difficulty: 1,
        timeCook: 10,
        price: 200,
        ingredients: ['Салат айсберг', 'Помидоры', 'Огурцы', 'Соль', 'Перец', 'Майонез'],
    },
    // {
    //     foodId: 2,
    //     cookBy: 'question',
    //     nameFood: 'яичница с тестом',
    //     difficulty: 1,
    //     timeCook: 10,
    //     ingredients: ['Яйца', 'Мука', 'Вода', 'Соль'],
    // },
    {
        foodId: 3,
        cookBy: 'pan',
        nameFood: 'яичница',
        difficulty: 1,
        timeCook: 5,
        ingredients: ['Яйца', 'Соль', 'Перец'],
    },
    {
        cookBy: 'pan',
        nameFood: 'яичница',
        ingredients: [],
    },
    // {
    //     foodId: 4,
    //     cookBy: 'pot',
    //     nameFood: 'макароны',
    //     difficulty: 2,
    //     timeCook: 15,
    //     price: 80,
    //     ingredients: ['Макароны', 'Соль'],
    // },
    // {
    //     foodId: 5,
    //     cookBy: 'oven',
    //     nameFood: 'запеченая курица',
    //     difficulty: 3,
    //     timeCook: 60,
    //     price: 350,
    //     ingredients: ['Курица', 'Соль', 'Перец', 'Паприка', 'Сухой чеснок'],
    // },
    // {
    //     foodId: 6,
    //     cookBy: 'microwave',
    //     nameFood: 'чебупели',
    //     difficulty: 0,
    //     timeCook: 3,
    //     price: 180,
    //     ingredients: ['Чебупели'],
    // },
    // {
    //     foodId: 7,
    //     cookBy: 'pot',
    //     nameFood: 'куриный суп',
    //     difficulty: 3,
    //     timeCook: 90,
    //     price: 450,
    //     ingredients: ['Макароны', 'Курица', 'Картофель', 'Морковь', 'Лук', 'Соль'],
    // },
    // {
    //     foodId: 8,
    //     cookBy: 'nothing',
    //     nameFood: 'копченая курица',
    //     difficulty: 0,
    //     timeCook: 0,
    //     price: 220,
    //     ingredients: ['Копченая курица'],
    // },
];
