import { ICard } from '@/components/types/types';

export const cards: ICard[] = [
    {
        cookBy: 'knife',
        nameFood: 'салат',
        difficulty: 1,
        timeCook: 10,
        price: 200,
        ingredients: ['Салат айсберг', 'Помидоры', 'Огурцы', 'Соль', 'Перец', 'Майонез'],
    },
    {
        cookBy: 'question',
        nameFood: 'яичница с тестом',
        difficulty: 1,
        timeCook: 10,
        price: 18,
        ingredients: ['Яйца', 'Мука', 'Вода', 'Соль'],
    },
    {
        cookBy: 'pan',
        nameFood: 'яичница',
        difficulty: 1,
        timeCook: 5,
        price: 20,
        ingredients: ['Яйца', 'Соль', 'Перец'],
    },
    {
        cookBy: 'pot',
        nameFood: 'макароны',
        difficulty: 2,
        timeCook: 15,
        price: 80,
        ingredients: ['Макароны', 'Соль'],
    },
    {
        cookBy: 'oven',
        nameFood: 'запеченая курица',
        difficulty: 3,
        timeCook: 60,
        price: 350,
        ingredients: ['Курица', 'Соль', 'Перец', 'Паприка', 'Сухой чеснок'],
    },
    {
        cookBy: 'microwave',
        nameFood: 'чебупели',
        difficulty: 0,
        timeCook: 3,
        price: 180,
        ingredients: ['Чебупели'],
    },
    {
        cookBy: 'pot',
        nameFood: 'куриный суп',
        difficulty: 3,
        timeCook: 90,
        price: 450,
        ingredients: ['Макароны', 'Курица', 'Картофель', 'Морковь', 'Лук', 'Соль'],
    },
    {
        cookBy: 'nothing',
        nameFood: 'копченая курица',
        difficulty: 0,
        timeCook: 0,
        price: 220,
        ingredients: ['Копченая курица'],
    },
];
